### ISSUE TITLE
`imp-visit-buffer` opens a wrong URL

### ISSUE THREAD

**Issue by mphojele** [skeeto/impatient-mode#19]
I'm loving this plugin, very much. However, imp-visit-buffer seems to be confused about hosting because instead of a URL like this `localhost:8080/boo/boo/` it puts the name of my machine as host. There's nothing served there but writing the URL with localhost replacing my machine name works fine. Please help:)

**Comment by hackerb9** [comment]
It's a bug where impatient mode is not using the proper httpd-host address. Here's a patch that fixes it:

```elisp
(defun imp-visit-buffer (&optional arg)
  "Visit the current buffer in a browser.
If given a prefix argument, visit the buffer listing instead."
  (interactive "P")
  (unless (process-status "httpd")
    (httpd-start))
  (unless impatient-mode
    (let ((url (format "http://%s:%d/imp/"
		       (cl-case httpd-host
			 ((nil) "0.0.0.0")
			 ((local) "localhost")
			 (otherwise httpd-host))
		       (system-name) httpd-port)))
      (unless arg
	(setq url (format "%slive/%s/" url (url-hexify-string (buffer-name)))))
      (browse-url url))))
```

**Comment by mitchet** [comment]
Thank you🤗

**Comment by mphojele** [comment]
I should have closed this issue a long time ago. Sorry.
