### ISSUE TITLE
Less impatience

### ISSUE THREAD

**Issue by mphojele** [skeeto/impatient-mode#23]
Is it possible to set the amount of impatience? 

I know simply calling `httpd-start` followed by its command to server the directory means i get a server that serves the actual files and i see changes as i save, which is at impatience level _0_.

However, enabling `impatient-mode` shoots the impatience level to a _100_ because it servers the buffers and i see changes as i edit. What more can I wish for?

How about having the impatience level at _50_? It serves the buffers, however, I do not see changes as I edit, instead I have to do manual browser refreshes. I'm left with only the joy that I don't have to save the files.

Sorry for being so poetic, but I say this because I'm seeing astronomical numbers with regards to my RAM. maybe it's Firefox, and I don't know how to tweak it to not bunk so much resources. It was around over 1GB and I only had one window and tab open.

**Comment by skeeto** [comment]
Have you tried adjusting impatient-mode-delay? That might be close to 
what you want. There's currently no "public" function to manually 
trigger an update, but imp--after-timeout is basically that.

**Comment by mphojele** [comment]
I'll look into it, thank you
