### ISSUE TITLE
type of impatient-mode-delay custom variable

### ISSUE THREAD

**Issue by xavierr** [skeeto/impatient-mode#37]
From the documentation string, it looks the custom variable impatient-mode-delay should be a number but it is set as a boolean:

``` elisp
(defcustom impatient-mode-delay nil
  "The delay in seconds between a keypress and the browser reload.
Set to nil for no delay"
  :group 'impatient
  :type 'boolean)
```

**Comment by skeeto** [comment]
Whoops, you're right. That was probably a copy-paste error.

**Comment by xavierr** [comment]
Thanks! I wrote a fix for myself but I am glad I did not send it : Yours is so much more elegant!
